export { PHPEngine, PHPEngineOptions } from "./src/PHPEngine";
export { PHPContext, PHPContextOptions } from "./src/PHPContext";
export { PHPExtension } from "./src/PHPExtension";
export { PHPError, PHPException, PHPTypeError, PHPParseError, PHPFatalError, PHPNotice, PHPWarning, ErrorException, } from "./src/runtime/errors/PHPError";
export { PHPObject, PHPClass, PHPMethodMetadata, PHPPropertyMetadata, PHPParameterMetadata } from "./src/runtime/objects/PHPObject";
export { Superglobals } from "./src/runtime/superglobals/Superglobals";
export { OutputBufferStack } from "./src/runtime/output/OutputBuffer";
export { PHPParser } from "./src/parser/PHPParser";
export { ASTOptimizer } from "./src/parser/ASTOptimizer";
export { JSTranspiler } from "./src/parser/JSTranspiler";
export { runHTTPServer } from "./src/cli/php-http-server";
export { runFPM } from "./src/cli/php-fpm";
export { defineFunction, FunctionMetaOptions, Reflection, ReflectionClass, ReflectionMethod, ReflectionProperty, ReflectionFunction, ReflectionParameter, ReflectionType, } from "./src/runtime/reflection/Reflection";
export { NodeJSExtension, NodeJSObject, NodeJSService, wrapJSValue, unwrapPHPValue, } from "./src/extensions/nodejs/nodejs";
