"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ReflectionType = exports.ReflectionParameter = exports.ReflectionFunction = exports.ReflectionProperty = exports.ReflectionMethod = exports.ReflectionClass = exports.Reflection = exports.defineFunction = exports.JSTranspiler = exports.ASTOptimizer = exports.PHPParser = exports.OutputBufferStack = exports.Superglobals = exports.PHPClass = exports.PHPObject = exports.PHPFatalError = exports.PHPParseError = exports.PHPTypeError = exports.PHPException = exports.PHPError = exports.PHPExtension = exports.PHPContext = exports.PHPEngine = void 0;
var PHPEngine_1 = require("./src/PHPEngine");
Object.defineProperty(exports, "PHPEngine", { enumerable: true, get: function () { return PHPEngine_1.PHPEngine; } });
var PHPContext_1 = require("./src/PHPContext");
Object.defineProperty(exports, "PHPContext", { enumerable: true, get: function () { return PHPContext_1.PHPContext; } });
var PHPExtension_1 = require("./src/PHPExtension");
Object.defineProperty(exports, "PHPExtension", { enumerable: true, get: function () { return PHPExtension_1.PHPExtension; } });
var PHPError_1 = require("./src/runtime/errors/PHPError");
Object.defineProperty(exports, "PHPError", { enumerable: true, get: function () { return PHPError_1.PHPError; } });
Object.defineProperty(exports, "PHPException", { enumerable: true, get: function () { return PHPError_1.PHPException; } });
Object.defineProperty(exports, "PHPTypeError", { enumerable: true, get: function () { return PHPError_1.PHPTypeError; } });
Object.defineProperty(exports, "PHPParseError", { enumerable: true, get: function () { return PHPError_1.PHPParseError; } });
Object.defineProperty(exports, "PHPFatalError", { enumerable: true, get: function () { return PHPError_1.PHPFatalError; } });
var PHPObject_1 = require("./src/runtime/objects/PHPObject");
Object.defineProperty(exports, "PHPObject", { enumerable: true, get: function () { return PHPObject_1.PHPObject; } });
Object.defineProperty(exports, "PHPClass", { enumerable: true, get: function () { return PHPObject_1.PHPClass; } });
var Superglobals_1 = require("./src/runtime/superglobals/Superglobals");
Object.defineProperty(exports, "Superglobals", { enumerable: true, get: function () { return Superglobals_1.Superglobals; } });
var OutputBuffer_1 = require("./src/runtime/output/OutputBuffer");
Object.defineProperty(exports, "OutputBufferStack", { enumerable: true, get: function () { return OutputBuffer_1.OutputBufferStack; } });
var PHPParser_1 = require("./src/parser/PHPParser");
Object.defineProperty(exports, "PHPParser", { enumerable: true, get: function () { return PHPParser_1.PHPParser; } });
var ASTOptimizer_1 = require("./src/parser/ASTOptimizer");
Object.defineProperty(exports, "ASTOptimizer", { enumerable: true, get: function () { return ASTOptimizer_1.ASTOptimizer; } });
var JSTranspiler_1 = require("./src/parser/JSTranspiler");
Object.defineProperty(exports, "JSTranspiler", { enumerable: true, get: function () { return JSTranspiler_1.JSTranspiler; } });
var Reflection_1 = require("./src/runtime/reflection/Reflection");
Object.defineProperty(exports, "defineFunction", { enumerable: true, get: function () { return Reflection_1.defineFunction; } });
Object.defineProperty(exports, "Reflection", { enumerable: true, get: function () { return Reflection_1.Reflection; } });
Object.defineProperty(exports, "ReflectionClass", { enumerable: true, get: function () { return Reflection_1.ReflectionClass; } });
Object.defineProperty(exports, "ReflectionMethod", { enumerable: true, get: function () { return Reflection_1.ReflectionMethod; } });
Object.defineProperty(exports, "ReflectionProperty", { enumerable: true, get: function () { return Reflection_1.ReflectionProperty; } });
Object.defineProperty(exports, "ReflectionFunction", { enumerable: true, get: function () { return Reflection_1.ReflectionFunction; } });
Object.defineProperty(exports, "ReflectionParameter", { enumerable: true, get: function () { return Reflection_1.ReflectionParameter; } });
Object.defineProperty(exports, "ReflectionType", { enumerable: true, get: function () { return Reflection_1.ReflectionType; } });
//# sourceMappingURL=index.js.map