import { PHPContext } from "../PHPContext.js";
import type { PHPEngine } from "../PHPEngine.js";
import { PHPReference } from "./PHPVariable.js";
export declare class ArrayRuntime {
    static count(ctx: PHPContext, arrayOrCountableArg?: PHPReference): number;
    static array_keys(ctx: PHPContext, inputArg?: PHPReference): any[];
    static array_values(ctx: PHPContext, inputArg?: PHPReference): any[];
    static array_flip(ctx: PHPContext, inputArg?: PHPReference): Record<string, any>;
    static array_reverse(ctx: PHPContext, arrayArg?: PHPReference): any[];
    static in_array(ctx: PHPContext, needleArg?: PHPReference, haystackArg?: PHPReference, strictArg?: PHPReference): boolean;
    static array_search(ctx: PHPContext, needleArg?: PHPReference, haystackArg?: PHPReference, strictArg?: PHPReference): any | false;
    static array_key_exists(ctx: PHPContext, keyArg?: PHPReference, searchArg?: PHPReference): boolean;
    static array_merge(ctx: PHPContext, ...arraysArgs: PHPReference[]): any;
    static array_combine(ctx: PHPContext, keysArg?: PHPReference, valuesArg?: PHPReference): Record<string, any> | false;
    static array_fill(ctx: PHPContext, startIndexArg?: PHPReference, countArg?: PHPReference, valueArg?: PHPReference): any[] | Record<string, any>;
    static array_fill_keys(ctx: PHPContext, keysArg?: PHPReference, valueArg?: PHPReference): Record<string, any>;
    static array_intersect(ctx: PHPContext, arrayArg?: PHPReference, ...othersArgs: PHPReference[]): any;
    static array_diff(ctx: PHPContext, arrayArg?: PHPReference, ...othersArgs: PHPReference[]): any;
    static array_intersect_key(ctx: PHPContext, arrayArg?: PHPReference, ...othersArgs: PHPReference[]): any;
    static array_diff_key(ctx: PHPContext, arrayArg?: PHPReference, ...othersArgs: PHPReference[]): any;
    static array_slice(ctx: PHPContext, arrayArg?: PHPReference, offsetArg?: PHPReference, lengthArg?: PHPReference): any[];
    static array_change_key_case(ctx: PHPContext, arrayArg?: PHPReference, caseArg?: PHPReference): Record<string, any> | null;
    static array_push(ctx: PHPContext, arrayArg?: PHPReference, ...varargsArgs: PHPReference[]): number;
    static array_pop(ctx: PHPContext, arrayArg?: PHPReference): any;
    static array_shift(ctx: PHPContext, arrayArg?: PHPReference): any;
    static array_unshift(ctx: PHPContext, arrayArg?: PHPReference, ...varargsArgs: PHPReference[]): number;
    static array_unique(ctx: PHPContext, arrayArg?: PHPReference): any;
    static array_column(ctx: PHPContext, arrayArg?: PHPReference, columnKeyArg?: PHPReference): any[];
    static sort(ctx: PHPContext, arrayArg?: PHPReference): boolean;
    static rsort(ctx: PHPContext, arrayArg?: PHPReference): boolean;
    static ksort(ctx: PHPContext, arrayArg?: PHPReference, flagsArg?: PHPReference): boolean;
    static array_map(ctx: PHPContext, callbackArg?: PHPReference, ...arraysArgs: PHPReference[]): Promise<any>;
    static array_filter(ctx: PHPContext, arrayArg?: PHPReference, callbackArg?: PHPReference, modeArg?: PHPReference): Promise<any>;
    static array_key_first(ctx: PHPContext, arrayArg?: PHPReference): any | null;
    static array_key_last(ctx: PHPContext, arrayArg?: PHPReference): any | null;
    private static getEntries;
    static reset(ctx: PHPContext, arrayArg?: PHPReference): any;
    static current(ctx: PHPContext, arrayArg?: PHPReference): any;
    static next(ctx: PHPContext, arrayArg?: PHPReference): any;
    static prev(ctx: PHPContext, arrayArg?: PHPReference): any;
    static end(ctx: PHPContext, arrayArg?: PHPReference): any;
    static key(ctx: PHPContext, arrayArg?: PHPReference): any;
    static each(ctx: PHPContext, arrayArg?: PHPReference): any;
    static functions: {
        count: typeof ArrayRuntime.count;
        sizeof: typeof ArrayRuntime.count;
        array_keys: typeof ArrayRuntime.array_keys;
        array_values: typeof ArrayRuntime.array_values;
        array_flip: typeof ArrayRuntime.array_flip;
        array_reverse: typeof ArrayRuntime.array_reverse;
        in_array: typeof ArrayRuntime.in_array;
        array_search: typeof ArrayRuntime.array_search;
        array_key_exists: typeof ArrayRuntime.array_key_exists;
        key_exists: typeof ArrayRuntime.array_key_exists;
        array_merge: typeof ArrayRuntime.array_merge;
        array_combine: typeof ArrayRuntime.array_combine;
        array_fill_keys: typeof ArrayRuntime.array_fill_keys;
        array_fill: typeof ArrayRuntime.array_fill;
        array_intersect: typeof ArrayRuntime.array_intersect;
        array_diff: typeof ArrayRuntime.array_diff;
        array_intersect_key: typeof ArrayRuntime.array_intersect_key;
        array_diff_key: typeof ArrayRuntime.array_diff_key;
        array_slice: typeof ArrayRuntime.array_slice;
        array_push: typeof ArrayRuntime.array_push;
        array_pop: typeof ArrayRuntime.array_pop;
        array_shift: typeof ArrayRuntime.array_shift;
        array_unshift: typeof ArrayRuntime.array_unshift;
        array_unique: typeof ArrayRuntime.array_unique;
        array_column: typeof ArrayRuntime.array_column;
        sort: typeof ArrayRuntime.sort;
        rsort: typeof ArrayRuntime.rsort;
        ksort: typeof ArrayRuntime.ksort;
        array_map: typeof ArrayRuntime.array_map;
        array_filter: typeof ArrayRuntime.array_filter;
        array_key_first: typeof ArrayRuntime.array_key_first;
        array_change_key_case: typeof ArrayRuntime.array_change_key_case;
        array_key_last: typeof ArrayRuntime.array_key_last;
        current: typeof ArrayRuntime.current;
        pos: typeof ArrayRuntime.current;
        reset: typeof ArrayRuntime.reset;
        end: typeof ArrayRuntime.end;
        key: typeof ArrayRuntime.key;
        next: typeof ArrayRuntime.next;
        prev: typeof ArrayRuntime.prev;
        each: typeof ArrayRuntime.each;
    };
    static register(engine: PHPEngine): void;
}
