import { PHPContext } from "../PHPContext";
import type { PHPEngine } from "../PHPEngine";
export declare class ArrayRuntime {
    static count(ctx: PHPContext, arrayOrCountable: any): number;
    static array_keys(ctx: PHPContext, input: any): any[];
    static array_values(ctx: PHPContext, input: any): any[];
    static array_flip(ctx: PHPContext, input: any): Record<string, any>;
    static array_reverse(ctx: PHPContext, array: any[]): any[];
    static in_array(ctx: PHPContext, needle: any, haystack: any, strict?: boolean): boolean;
    static array_search(ctx: PHPContext, needle: any, haystack: any, strict?: boolean): any | false;
    static array_key_exists(ctx: PHPContext, key: any, search: any): boolean;
    static array_merge(ctx: PHPContext, ...arrays: any[]): any;
    static array_combine(ctx: PHPContext, keys: any[], values: any[]): Record<string, any> | false;
    static array_fill(ctx: PHPContext, startIndex: number, count: number, value: any): any[] | Record<string, any>;
    static array_fill_keys(ctx: PHPContext, keys: any, value: any): Record<string, any>;
    static array_intersect(ctx: PHPContext, array: any, ...others: any[]): any;
    static array_slice(ctx: PHPContext, array: any[], offset: number, length?: number): any[];
    static array_push(ctx: PHPContext, array: any[], ...varargs: any[]): number;
    static array_pop(ctx: PHPContext, array: any[]): any;
    static array_shift(ctx: PHPContext, array: any[]): any;
    static array_unshift(ctx: PHPContext, array: any[], ...varargs: any[]): number;
    static array_unique(ctx: PHPContext, array: any): any;
    static array_column(ctx: PHPContext, array: any[], columnKey: string | number): any[];
    static sort(ctx: PHPContext, array: any[]): boolean;
    static rsort(ctx: PHPContext, array: any[]): boolean;
    static ksort(ctx: PHPContext, array: any, flags?: number): boolean;
    static array_map(ctx: PHPContext, callback: any, ...arrays: any[]): Promise<any[]>;
    static array_filter(ctx: PHPContext, array: any, callback?: any, mode?: number): Promise<any>;
    static array_key_first(ctx: PHPContext, array: any): any | null;
    static array_key_last(ctx: PHPContext, array: any): any | null;
    static functions: {
        count: typeof ArrayRuntime.count;
        sizeof: typeof ArrayRuntime.count;
        array_keys: typeof ArrayRuntime.array_keys;
        array_values: typeof ArrayRuntime.array_values;
        array_flip: typeof ArrayRuntime.array_flip;
        array_reverse: typeof ArrayRuntime.array_reverse;
        in_array: typeof ArrayRuntime.in_array;
        array_search: typeof ArrayRuntime.array_search;
        array_key_exists: typeof ArrayRuntime.array_key_exists;
        key_exists: typeof ArrayRuntime.array_key_exists;
        array_merge: typeof ArrayRuntime.array_merge;
        array_combine: typeof ArrayRuntime.array_combine;
        array_fill_keys: typeof ArrayRuntime.array_fill_keys;
        array_fill: typeof ArrayRuntime.array_fill;
        array_intersect: typeof ArrayRuntime.array_intersect;
        array_slice: typeof ArrayRuntime.array_slice;
        array_push: typeof ArrayRuntime.array_push;
        array_pop: typeof ArrayRuntime.array_pop;
        array_shift: typeof ArrayRuntime.array_shift;
        array_unshift: typeof ArrayRuntime.array_unshift;
        array_unique: typeof ArrayRuntime.array_unique;
        array_column: typeof ArrayRuntime.array_column;
        sort: typeof ArrayRuntime.sort;
        rsort: typeof ArrayRuntime.rsort;
        ksort: typeof ArrayRuntime.ksort;
        array_map: typeof ArrayRuntime.array_map;
        array_filter: typeof ArrayRuntime.array_filter;
        array_key_first: typeof ArrayRuntime.array_key_first;
        array_key_last: typeof ArrayRuntime.array_key_last;
    };
    static register(engine: PHPEngine): void;
}
