import type { PHPEngine } from "../PHPEngine";
import type { PHPContext } from "../PHPContext";
export declare class FileSystemRuntime {
    static fileowner(ctx: PHPContext, filename: string): Promise<number | false>;
    static fileperms(ctx: PHPContext, filename: string): Promise<number | false>;
    static glob(ctx: PHPContext, pattern: string, flags?: number): Promise<string[] | false>;
    static file(ctx: PHPContext, filepath: string, flags?: number): Promise<string[] | false>;
    static file_get_contents(ctx: PHPContext, filepath: string): Promise<string | false>;
    static file_put_contents(ctx: PHPContext, filepath: string, data: any, flags?: number): Promise<number | false>;
    static file_exists(ctx: PHPContext, filepath: string): Promise<boolean>;
    static is_dir(ctx: PHPContext, filepath: string): Promise<boolean>;
    static is_file(ctx: PHPContext, filepath: string): Promise<boolean>;
    static is_readable(ctx: PHPContext, filepath: string): Promise<boolean>;
    static is_writable(ctx: PHPContext, filepath: string): Promise<boolean>;
    static filesize(ctx: PHPContext, filepath: string): Promise<number | false>;
    static filemtime(ctx: PHPContext, filepath: string): Promise<number | false>;
    static realpath(ctx: PHPContext, filepath: string): Promise<string | false>;
    static basename(ctx: PHPContext, filepath: string, suffix?: string): string;
    static dirname(ctx: PHPContext, filepath: string): string;
    static pathinfo(ctx: PHPContext, filepath: string, flags?: number): Record<string, string>;
    static mkdir(ctx: PHPContext, dirpath: string, mode?: number, recursive?: boolean): Promise<boolean>;
    static rmdir(ctx: PHPContext, dirpath: string): Promise<boolean>;
    static unlink(ctx: PHPContext, filepath: string): Promise<boolean>;
    static rename(ctx: PHPContext, oldname: string, newname: string): Promise<boolean>;
    static copy(ctx: PHPContext, source: string, dest: string): Promise<boolean>;
    static tempnam(ctx: PHPContext, dir: string, prefix: string): Promise<string | false>;
    static sys_get_temp_dir(ctx?: PHPContext): string;
    static scandir(ctx: PHPContext, dirpath: string): Promise<string[] | false>;
    static constants: {
        GLOB_ERR: number;
        GLOB_MARK: number;
        GLOB_NOSORT: number;
        GLOB_NOCHECK: number;
        GLOB_NOESCAPE: number;
        GLOB_BRACE: number;
        GLOB_ONLYDIR: number;
    };
    static functions: {
        glob: typeof FileSystemRuntime.glob;
        fileowner: typeof FileSystemRuntime.fileowner;
        fileperms: typeof FileSystemRuntime.fileperms;
        file: typeof FileSystemRuntime.file;
        file_get_contents: typeof FileSystemRuntime.file_get_contents;
        file_put_contents: typeof FileSystemRuntime.file_put_contents;
        file_exists: typeof FileSystemRuntime.file_exists;
        is_dir: typeof FileSystemRuntime.is_dir;
        is_file: typeof FileSystemRuntime.is_file;
        is_readable: typeof FileSystemRuntime.is_readable;
        is_writable: typeof FileSystemRuntime.is_writable;
        filesize: typeof FileSystemRuntime.filesize;
        filemtime: typeof FileSystemRuntime.filemtime;
        realpath: typeof FileSystemRuntime.realpath;
        basename: typeof FileSystemRuntime.basename;
        dirname: typeof FileSystemRuntime.dirname;
        pathinfo: typeof FileSystemRuntime.pathinfo;
        mkdir: typeof FileSystemRuntime.mkdir;
        rmdir: typeof FileSystemRuntime.rmdir;
        unlink: typeof FileSystemRuntime.unlink;
        rename: typeof FileSystemRuntime.rename;
        copy: typeof FileSystemRuntime.copy;
        tempnam: typeof FileSystemRuntime.tempnam;
        sys_get_temp_dir: typeof FileSystemRuntime.sys_get_temp_dir;
        scandir: typeof FileSystemRuntime.scandir;
    };
    static register(engine: PHPEngine): void;
}
