import type { PHPEngine } from "../PHPEngine";
import type { PHPContext } from "../PHPContext";
import type { PHPReference } from "./PHPVariable";
export declare class FileSystemRuntime {
    static fileowner(ctx: PHPContext, filenameArg?: PHPReference): Promise<number | false>;
    static fileperms(ctx: PHPContext, filenameArg?: PHPReference): Promise<number | false>;
    static glob(ctx: PHPContext, patternArg?: PHPReference, flagsArg?: PHPReference): Promise<string[] | false>;
    static file(ctx: PHPContext, filepathArg?: PHPReference, flagsArg?: PHPReference): Promise<string[] | false>;
    static file_get_contents(ctx: PHPContext, filepathArg?: PHPReference): Promise<string | false>;
    static file_put_contents(ctx: PHPContext, filepathArg?: PHPReference, dataArg?: PHPReference, flagsArg?: PHPReference): Promise<number | false>;
    static file_exists(ctx: PHPContext, filepathArg?: PHPReference): Promise<boolean>;
    static is_dir(ctx: PHPContext, filepathArg?: PHPReference): Promise<boolean>;
    static is_file(ctx: PHPContext, filepathArg?: PHPReference): Promise<boolean>;
    static is_readable(ctx: PHPContext, filepathArg?: PHPReference): Promise<boolean>;
    static is_writable(ctx: PHPContext, filepathArg?: PHPReference): Promise<boolean>;
    static filesize(ctx: PHPContext, filepathArg?: PHPReference): Promise<number | false>;
    static filemtime(ctx: PHPContext, filepathArg?: PHPReference): Promise<number | false>;
    static realpath(ctx: PHPContext, filepathArg?: PHPReference): Promise<string | false>;
    static basename(ctx: PHPContext, filepathArg?: PHPReference, suffixArg?: PHPReference): string;
    static dirname(ctx: PHPContext, filepathArg?: PHPReference): string;
    static pathinfo(ctx: PHPContext, filepathArg?: PHPReference, flagsArg?: PHPReference): Record<string, string>;
    static mkdir(ctx: PHPContext, dirpathArg?: PHPReference, modeArg?: PHPReference, recursiveArg?: PHPReference): Promise<boolean>;
    static chmod(ctx: PHPContext, filenameArg?: PHPReference, modeArg?: PHPReference): Promise<boolean>;
    static rmdir(ctx: PHPContext, dirpathArg?: PHPReference): Promise<boolean>;
    static unlink(ctx: PHPContext, filepathArg?: PHPReference): Promise<boolean>;
    static rename(ctx: PHPContext, oldnameArg?: PHPReference, newnameArg?: PHPReference): Promise<boolean>;
    static copy(ctx: PHPContext, sourceArg?: PHPReference, destArg?: PHPReference): Promise<boolean>;
    static tempnam(ctx: PHPContext, dirArg?: PHPReference, prefixArg?: PHPReference): Promise<string | false>;
    static sys_get_temp_dir(ctx?: PHPContext): string;
    static scandir(ctx: PHPContext, dirpathArg?: PHPReference): Promise<string[] | false>;
    static constants: {
        glob_err: number;
        glob_mark: number;
        glob_nosort: number;
        glob_nocheck: number;
        glob_noescape: number;
        glob_brace: number;
        glob_onlydir: number;
        file_use_include_path: number;
        file_ignore_new_lines: number;
        file_skip_empty_lines: number;
        file_append: number;
    };
    static functions: {
        fileowner: typeof FileSystemRuntime.fileowner;
        fileperms: typeof FileSystemRuntime.fileperms;
        glob: typeof FileSystemRuntime.glob;
        file: typeof FileSystemRuntime.file;
        file_get_contents: typeof FileSystemRuntime.file_get_contents;
        file_put_contents: typeof FileSystemRuntime.file_put_contents;
        file_exists: typeof FileSystemRuntime.file_exists;
        is_dir: typeof FileSystemRuntime.is_dir;
        is_file: typeof FileSystemRuntime.is_file;
        is_readable: typeof FileSystemRuntime.is_readable;
        is_writable: typeof FileSystemRuntime.is_writable;
        filesize: typeof FileSystemRuntime.filesize;
        filemtime: typeof FileSystemRuntime.filemtime;
        realpath: typeof FileSystemRuntime.realpath;
        basename: typeof FileSystemRuntime.basename;
        dirname: typeof FileSystemRuntime.dirname;
        pathinfo: typeof FileSystemRuntime.pathinfo;
        mkdir: typeof FileSystemRuntime.mkdir;
        chmod: typeof FileSystemRuntime.chmod;
        rmdir: typeof FileSystemRuntime.rmdir;
        unlink: typeof FileSystemRuntime.unlink;
        rename: typeof FileSystemRuntime.rename;
        copy: typeof FileSystemRuntime.copy;
        tempnam: typeof FileSystemRuntime.tempnam;
        sys_get_temp_dir: typeof FileSystemRuntime.sys_get_temp_dir;
        scandir: typeof FileSystemRuntime.scandir;
    };
    static register(engine: PHPEngine): void;
}
