import type { PHPEngine } from "../PHPEngine";
import type { PHPContext } from "../PHPContext";
export declare class MathRuntime {
    static abs(ctx: PHPContext, num: number): number;
    static ceil(ctx: PHPContext, num: number): number;
    static floor(ctx: PHPContext, num: number): number;
    static round(ctx: PHPContext, num: number, precision?: number): number;
    static max(ctx: PHPContext, ...args: any[]): any;
    static min(ctx: PHPContext, ...args: any[]): any;
    static pow(ctx: PHPContext, base: number, exp: number): number;
    static sqrt(ctx: PHPContext, num: number): number;
    static rand(ctx: PHPContext, min?: number, max?: number): number;
    static mt_rand(ctx: PHPContext, min?: number, max?: number): number;
    static mt_getrandmax(ctx: PHPContext): number;
    static sin(ctx: PHPContext, num: number): number;
    static cos(ctx: PHPContext, num: number): number;
    static tan(ctx: PHPContext, num: number): number;
    static asin(ctx: PHPContext, num: number): number;
    static acos(ctx: PHPContext, num: number): number;
    static atan(ctx: PHPContext, num: number): number;
    static atan2(ctx: PHPContext, y: number, x: number): number;
    static log(ctx: PHPContext, num: number, base?: number): number;
    static log10(ctx: PHPContext, num: number): number;
    static exp(ctx: PHPContext, num: number): number;
    static fmod(ctx: PHPContext, x: number, y: number): number;
    static intdiv(ctx: PHPContext, x: number, y: number): number;
    static is_nan(ctx: PHPContext, num: number): boolean;
    static is_finite(ctx: PHPContext, num: number): boolean;
    static is_infinite(ctx: PHPContext, num: number): boolean;
    static pi(ctx: PHPContext): number;
    static deg2rad(ctx: PHPContext, num: number): number;
    static rad2deg(ctx: PHPContext, num: number): number;
    static base_convert(ctx: PHPContext, num: string, fromBase: number, toBase: number): string;
    static bindec(ctx: PHPContext, binaryString: string): number;
    static decbin(ctx: PHPContext, num: number): string;
    static dechex(ctx: PHPContext, num: number): string;
    static hexdec(ctx: PHPContext, hexString: string): number;
    static octdec(ctx: PHPContext, octString: string): number;
    static decoct(ctx: PHPContext, num: number): string;
    static functions: {
        abs: typeof MathRuntime.abs;
        ceil: typeof MathRuntime.ceil;
        floor: typeof MathRuntime.floor;
        round: typeof MathRuntime.round;
        max: typeof MathRuntime.max;
        min: typeof MathRuntime.min;
        pow: typeof MathRuntime.pow;
        sqrt: typeof MathRuntime.sqrt;
        rand: typeof MathRuntime.rand;
        mt_rand: typeof MathRuntime.mt_rand;
        mt_getrandmax: typeof MathRuntime.mt_getrandmax;
        sin: typeof MathRuntime.sin;
        cos: typeof MathRuntime.cos;
        tan: typeof MathRuntime.tan;
        asin: typeof MathRuntime.asin;
        acos: typeof MathRuntime.acos;
        atan: typeof MathRuntime.atan;
        atan2: typeof MathRuntime.atan2;
        log: typeof MathRuntime.log;
        log10: typeof MathRuntime.log10;
        exp: typeof MathRuntime.exp;
        fmod: typeof MathRuntime.fmod;
        intdiv: typeof MathRuntime.intdiv;
        is_nan: typeof MathRuntime.is_nan;
        is_finite: typeof MathRuntime.is_finite;
        is_infinite: typeof MathRuntime.is_infinite;
        pi: typeof MathRuntime.pi;
        deg2rad: typeof MathRuntime.deg2rad;
        rad2deg: typeof MathRuntime.rad2deg;
        base_convert: typeof MathRuntime.base_convert;
        bindec: typeof MathRuntime.bindec;
        decbin: typeof MathRuntime.decbin;
        dechex: typeof MathRuntime.dechex;
        hexdec: typeof MathRuntime.hexdec;
        octdec: typeof MathRuntime.octdec;
        decoct: typeof MathRuntime.decoct;
    };
    static register(engine: PHPEngine): void;
}
