import type { PHPEngine } from "../PHPEngine.js";
import type { PHPContext } from "../PHPContext.js";
import { PHPReference } from "./PHPVariable.js";
export declare class MathRuntime {
    static abs(ctx: PHPContext, num?: PHPReference): number;
    static ceil(ctx: PHPContext, num?: PHPReference): number;
    static floor(ctx: PHPContext, num?: PHPReference): number;
    static round(ctx: PHPContext, num?: PHPReference, precisionArg?: PHPReference): number;
    static max(ctx: PHPContext, ...args: PHPReference[]): any;
    static min(ctx: PHPContext, ...args: PHPReference[]): any;
    static pow(ctx: PHPContext, baseArg?: PHPReference, expArg?: PHPReference): number;
    static sqrt(ctx: PHPContext, numArg?: PHPReference): number;
    static rand(ctx: PHPContext, minArg?: PHPReference, maxArg?: PHPReference): number;
    static mt_rand(ctx: PHPContext, minArg?: PHPReference, maxArg?: PHPReference): number;
    static random_int(ctx: PHPContext, minArg?: PHPReference, maxArg?: PHPReference): number;
    static mt_getrandmax(ctx: PHPContext): number;
    static sin(ctx: PHPContext, numArg?: PHPReference): number;
    static cos(ctx: PHPContext, numArg?: PHPReference): number;
    static tan(ctx: PHPContext, numArg?: PHPReference): number;
    static asin(ctx: PHPContext, numArg?: PHPReference): number;
    static acos(ctx: PHPContext, numArg?: PHPReference): number;
    static atan(ctx: PHPContext, numArg?: PHPReference): number;
    static atan2(ctx: PHPContext, yArg?: PHPReference, xArg?: PHPReference): number;
    static log(ctx: PHPContext, numArg?: PHPReference, baseArg?: PHPReference): number;
    static log10(ctx: PHPContext, numArg?: PHPReference): number;
    static exp(ctx: PHPContext, numArg?: PHPReference): number;
    static fmod(ctx: PHPContext, xArg?: PHPReference, yArg?: PHPReference): number;
    static intdiv(ctx: PHPContext, xArg?: PHPReference, yArg?: PHPReference): number;
    static is_nan(ctx: PHPContext, numArg?: PHPReference): boolean;
    static is_finite(ctx: PHPContext, numArg?: PHPReference): boolean;
    static is_infinite(ctx: PHPContext, numArg?: PHPReference): boolean;
    static pi(ctx: PHPContext): number;
    static deg2rad(ctx: PHPContext, numArg?: PHPReference): number;
    static rad2deg(ctx: PHPContext, numArg?: PHPReference): number;
    static base_convert(ctx: PHPContext, numArg?: PHPReference, fromBaseArg?: PHPReference, toBaseArg?: PHPReference): string;
    static bindec(ctx: PHPContext, binaryStringArg?: PHPReference): number;
    static decbin(ctx: PHPContext, numArg?: PHPReference): string;
    static dechex(ctx: PHPContext, numArg?: PHPReference): string;
    static hexdec(ctx: PHPContext, hexStringArg?: PHPReference): number;
    static octdec(ctx: PHPContext, octStringArg?: PHPReference): number;
    static decoct(ctx: PHPContext, numArg?: PHPReference): string;
    static functions: {
        abs: typeof MathRuntime.abs;
        ceil: typeof MathRuntime.ceil;
        floor: typeof MathRuntime.floor;
        round: typeof MathRuntime.round;
        max: typeof MathRuntime.max;
        min: typeof MathRuntime.min;
        pow: typeof MathRuntime.pow;
        sqrt: typeof MathRuntime.sqrt;
        rand: typeof MathRuntime.rand;
        mt_rand: typeof MathRuntime.mt_rand;
        random_int: typeof MathRuntime.random_int;
        mt_getrandmax: typeof MathRuntime.mt_getrandmax;
        sin: typeof MathRuntime.sin;
        cos: typeof MathRuntime.cos;
        tan: typeof MathRuntime.tan;
        asin: typeof MathRuntime.asin;
        acos: typeof MathRuntime.acos;
        atan: typeof MathRuntime.atan;
        atan2: typeof MathRuntime.atan2;
        log: typeof MathRuntime.log;
        log10: typeof MathRuntime.log10;
        exp: typeof MathRuntime.exp;
        fmod: typeof MathRuntime.fmod;
        intdiv: typeof MathRuntime.intdiv;
        is_nan: typeof MathRuntime.is_nan;
        is_finite: typeof MathRuntime.is_finite;
        is_infinite: typeof MathRuntime.is_infinite;
        pi: typeof MathRuntime.pi;
        deg2rad: typeof MathRuntime.deg2rad;
        rad2deg: typeof MathRuntime.rad2deg;
        base_convert: typeof MathRuntime.base_convert;
        bindec: typeof MathRuntime.bindec;
        decbin: typeof MathRuntime.decbin;
        dechex: typeof MathRuntime.dechex;
        hexdec: typeof MathRuntime.hexdec;
        octdec: typeof MathRuntime.octdec;
        decoct: typeof MathRuntime.decoct;
    };
    static register(engine: PHPEngine): void;
}
