import { PHPContext } from "../PHPContext.js";
import type { PHPEngine } from "../PHPEngine.js";
import { PHPReference } from "./PHPVariable.js";
export declare class NetworkingRuntime {
    static urlencode(ctx: PHPContext | null, valueArg?: PHPReference, raw?: boolean): string;
    static urldecode(ctx: PHPContext | null, valueArg?: PHPReference, raw?: boolean): string;
    static gethostname(ctx?: PHPContext): string;
    static gethostbyname(ctx: PHPContext | null, hostnameArg?: PHPReference): Promise<string>;
    static gethostbyaddr(ctx: PHPContext | null, ipArg?: PHPReference): Promise<string | false>;
    static ip2long(ctx: PHPContext | null, ipArg?: PHPReference): number | false;
    static long2ip(ctx: PHPContext | null, numArg?: PHPReference): string | false;
    static parse_url(ctx: PHPContext | null, urlStrArg?: PHPReference, componentArg?: PHPReference): any;
    static http_build_query(ctx: PHPContext | null, dataArg?: PHPReference, numericPrefixArg?: PHPReference, argSeparatorArg?: PHPReference): string;
    static header(ctx: PHPContext, headerStrArg?: any, replaceArg?: any, codeArg?: any): void;
    static setcookie(ctx: PHPContext, nameArg?: PHPReference, valueArg?: PHPReference, expiresArg?: PHPReference, pathArg?: PHPReference, domainArg?: PHPReference, secureArg?: PHPReference, httponlyArg?: PHPReference): boolean;
    static setrawcookie(ctx: PHPContext, nameArg?: PHPReference, valueArg?: PHPReference, expiresArg?: PHPReference, pathArg?: PHPReference, domainArg?: PHPReference, secureArg?: PHPReference, httponlyArg?: PHPReference): boolean;
    static header_remove(ctx: PHPContext, nameArg?: PHPReference): void;
    static headers_list(ctx: PHPContext): string[];
    static headers_sent(ctx: PHPContext): boolean;
    static http_response_code(ctx: PHPContext, codeArg?: PHPReference): number | boolean;
    static functions: {
        gethostname: typeof NetworkingRuntime.gethostname;
        gethostbyname: typeof NetworkingRuntime.gethostbyname;
        gethostbyaddr: typeof NetworkingRuntime.gethostbyaddr;
        ip2long: typeof NetworkingRuntime.ip2long;
        long2ip: typeof NetworkingRuntime.long2ip;
        parse_url: typeof NetworkingRuntime.parse_url;
        urlencode: (ctx: PHPContext, value?: PHPReference) => string;
        rawurlencode: (ctx: PHPContext, value?: PHPReference) => string;
        urldecode: (ctx: PHPContext, value?: PHPReference) => string;
        rawurldecode: (ctx: PHPContext, value?: PHPReference) => string;
        http_build_query: typeof NetworkingRuntime.http_build_query;
        header: typeof NetworkingRuntime.header;
        setcookie: typeof NetworkingRuntime.setcookie;
        setrawcookie: typeof NetworkingRuntime.setrawcookie;
        header_remove: typeof NetworkingRuntime.header_remove;
        headers_list: typeof NetworkingRuntime.headers_list;
        headers_sent: typeof NetworkingRuntime.headers_sent;
        http_response_code: typeof NetworkingRuntime.http_response_code;
    };
    static register(engine: PHPEngine): void;
}
